### ISSUE TITLE
Errors with authentication

### ISSUE THREAD

**Issue by michael** [substance/archivist#48]
I see this from time to time. Can you check what could be the cause? It happens when i use a fresh machine, where session cookie is not yet there.

```
12:16:40 web.1  | Error: Error getting collection: sessions <TypeError: Cannot read property 'hasListIndexesCommand' of undefined>
12:16:40 web.1  |     at /Users/michael/projects/substance/archivist_web/node_modules/connect-mongostore/lib/connect-mongostore.js:110:22
12:16:40 web.1  |     at Db.collection (/Users/michael/projects/substance/archivist_web/node_modules/connect-mongostore/node_modules/mongodb/lib/mongodb/db.js:501:27)
12:16:40 web.1  |     at MongoStore.getCollection (/Users/michael/projects/substance/archivist_web/node_modules/connect-mongostore/lib/connect-mongostore.js:109:13)
12:16:40 web.1  |     at MongoStore.get (/Users/michael/projects/substance/archivist_web/node_modules/connect-mongostore/lib/connect-mongostore.js:133:10)
12:16:40 web.1  |     at session (/Users/michael/projects/substance/archivist_web/node_modules/express-session/index.js:392:11)
12:16:40 web.1  |     at Layer.handle [as handle_request] (/Users/michael/projects/substance/archivist_web/node_modules/express/lib/router/layer.js:82:5)
12:16:40 web.1  |     at trim_prefix (/Users/michael/projects/substance/archivist_web/node_modules/express/lib/router/index.js:302:13)
12:16:40 web.1  |     at /Users/michael/projects/substance/archivist_web/node_modules/express/lib/router/index.js:270:7
12:16:40 web.1  |     at Function.proto.process_params (/Users/michael/projects/substance/archivist_web/node_modules/express/lib/router/index.js:321:12)
12:16:40 web.1  |     at next (/Users/michael/projects/substance/archivist_web/node_modules/express/lib/router/index.js:261:10)
12:16:41 web.1  | Error: No replica set primary available for query with ReadPreference PRIMARY
12:16:41 web.1  |     at ReplSet.checkoutReader (/Users/michael/projects/substance/archivist_web/node_modules/connect-mongostore/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:613:14)
12:16:41 web.1  |     at Cursor.nextObject (/Users/michael/projects/substance/archivist_web/node_modules/connect-mongostore/node_modules/mongodb/lib/mongodb/cursor.js:734:48)
12:16:41 web.1  |     at Collection.findOne (/Users/michael/projects/substance/archivist_web/node_modules/connect-mongostore/node_modules/mongodb/lib/mongodb/collection/query.js:162:10)
12:16:41 web.1  |     at /Users/michael/projects/substance/archivist_web/node_modules/connect-mongostore/lib/connect-mongostore.js:134:18
12:16:41 web.1  |     at MongoStore.getCollection (/Users/michael/projects/substance/archivist_web/node_modules/connect-mongostore/lib/connect-mongostore.js:103:13)
12:16:41 web.1  |     at MongoStore.get (/Users/michael/projects/substance/archivist_web/node_modules/connect-mongostore/lib/connect-mongostore.js:133:10)
12:16:41 web.1  |     at session (/Users/michael/projects/substance/archivist_web/node_modules/express-session/index.js:392:11)
12:16:41 web.1  |     at Layer.handle [as handle_request] (/Users/michael/projects/substance/archivist_web/node_modules/express/lib/router/layer.js:82:5)
12:16:41 web.1  |     at trim_prefix (/Users/michael/projects/substance/archivist_web/node_modules/express/lib/router/index.js:302:13)
12:16:41 web.1  |     at /Users/michael/projects/substance/archivist_web/node_modules/express/lib/router/index.js:270:
```

**Comment by Integral** [comment]
I guess you receive this only if you make request right after connection with mongo has been established.

**Comment by michael** [comment]
not critical according to daniel.. removing from January Alpha mile stone.

**Comment by Integral** [comment]
fixed
