### ISSUE TITLE
strange error that happens every now and then

### ISSUE THREAD

**Issue by michael** [substance/archivist#61]
```
Error: No replica set primary available for query with ReadPreference PRIMARY
   at ReplSet.checkoutReader (/Users/michael/projects/substance/archivist/node_modules/connect-mongostore/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:613:14)
   at Cursor.nextObject (/Users/michael/projects/substance/archivist/node_modules/connect-mongostore/node_modules/mongodb/lib/mongodb/cursor.js:734:48)
   at Collection.findOne (/Users/michael/projects/substance/archivist/node_modules/connect-mongostore/node_modules/mongodb/lib/mongodb/collection/query.js:162:10)
   at /Users/michael/projects/substance/archivist/node_modules/connect-mongostore/lib/connect-mongostore.js:134:18
   at MongoStore.getCollection (/Users/michael/projects/substance/archivist/node_modules/connect-mongostore/lib/connect-mongostore.js:103:13)
   at MongoStore.get (/Users/michael/projects/substance/archivist/node_modules/connect-mongostore/lib/connect-mongostore.js:133:10)
   at session (/Users/michael/projects/substance/archivist/node_modules/express-session/index.js:392:11)
   at Layer.handle [as handle_request] (/Users/michael/projects/substance/archivist/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/Users/michael/projects/substance/archivist/node_modules/express/lib/router/index.js:302:13)
   at /Users/michael/projects/substance/archivist/node_modules/express/lib/router/index.js:270:7
```

**Comment by Integral** [comment]
I've seen this error only if you make requests right after connection with mongo has been established as with authentication.

**Comment by Integral** [comment]
fixed
