### ISSUE TITLE
Project configuration (compress) broken

### ISSUE THREAD

**Issue by oliver----** [substance/archivist#66]
```bash
> substance-archivist@0.0.1 prepare /Users/oliver/projects/substance/archivist
> gulp compress

[15:23:34] Using gulpfile ~/projects/substance/archivist/gulpfile.js
[15:23:34] Starting 'compress'...
[15:23:40] Finished 'compress' after 5.89 s

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Command failed: remote: Repository not found.
fatal: repository 'https://github.com/assets/40px.png/' not found

    at error (/Users/oliver/projects/substance/archivist/node_modules/duo/node_modules/duo-package/node_modules/gh-resolve/index.js:177:10)
    at /Users/oliver/projects/substance/archivist/node_modules/duo/node_modules/duo-package/node_modules/gh-resolve/index.js:69:37
    at ChildProcess.exithandler (child_process.js:651:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)

npm ERR! substance-archivist@0.0.1 prepare: `gulp compress`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the substance-archivist@0.0.1 prepare script.
npm ERR! This is most likely a problem with the substance-archivist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp compress
npm ERR! You can get their info via:
npm ERR!     npm owner ls substance-archivist
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "prepare"
npm ERR! cwd /Users/oliver/projects/substance/archivist
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/oliver/projects/substance/archivist/npm-debug.log
npm ERR! not ok code 0
```

**Comment by Integral** [comment]
@oliver---- when did you pull last time?

**Comment by oliver----** [comment]
just now...

**Comment by Integral** [comment]
confirmed, still trying to do anything

**Comment by Integral** [comment]
could you try now?

**Comment by Integral** [comment]
please reopen if you still have errors

**Comment by oliver----** [comment]
Yep. It works.
